branches:
  only:
   - prod
   - staging
language: ruby
cache: bundler
sudo: false
rvm:
- 2.4.0
script: 
- bundle exec jekyll build --config _config.yml,_deployment_${TRAVIS_BRANCH}/_config.yml
after_success: 
- bundle exec s3_website push --config-dir _deployment_${TRAVIS_BRANCH}
