title: The Splunk Gallery
description: > 
  The community supported collection of Splunk Artifacts, Media, and Stories

mediabase: https://media.splunkgallery.com

collections:
  entries:
    permalink: /:collection/:name/
    output: true
  people:
    permalink: /:collection/:name/
    output: true

theme: jekyll-theme-slate

repository: acharlieh/splunk_gallery

defaults:
  - scope:
      path: ""
      type: entries
    values:
      layout: item
  - scope:
      path: ""
      type: people
    values:
      layout: person

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - create-staging.sh

plugins:
  - jekyll-default-layout
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-sitemap
